# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgoqdpWry4rGVEwxPYMszp1I_WhvzGNL

Language Detection Model : Machine Learning & NLP
"""

import numpy as np
import pandas as pd

data = pd.read_csv('/content/language.csv')

from google.colab import drive
drive.mount('/content/drive')

data

# Correct the typo in the module name
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB # Correct the typo in the class name

data.isnull().sum()

data['language'].value_counts()

data.dtypes

x = np.array(data['Text'])
y = np.array(data['language'])

print(x)
print(y)

cv = CountVectorizer()
x =cv.fit_transform(x)

x_train,x_test,y_train,y=train_test_split(x,y,test_size=0.33,random_state=42)

x_train

print(x)

y_train

model=MultinomialNB()
model.fit(x_train,y_train)
model.score(x_train,y_train)

user = input('Enter a text : ')
data = cv.transform([user]).toarray()
output = model.predict(data)
print(output)